service: woahlife
org: seancsnyder
plugins:
  - serverless-pseudo-parameters
  - serverless-plugin-aws-alerts
  - serverless-python-requirements
  - serverless-domain-manager
custom:
  pythonRequirements:
    dockerizePip: true
  alerts:
    topics:
      alarm:
        topic: ${self:service}-${self:provider.stage}-alarm
        notifications:
          - protocol: email
            endpoint: noreply@snyderitis.com
    definitions:
      functionErrors:
        namespace: AWS/Lambda
        metric: Errors
        threshold: 1
        statistic: Sum
        period: 60
        evaluationPeriods: 1
        datapointsToAlarm: 1
        comparisonOperator: GreaterThanOrEqualToThreshold
        treatMissingData: notBreaching
    alarms:
      - functionInvocations
      - functionErrors
  rootDomain: woahlife.com
  customDomain:
    domainName: api-${self:provider.stage}.${self:custom.rootDomain}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource:
        - !Sub arn:aws:logs:#{AWS::Region}:#{AWS::AccountId}:log-group:/aws/lambda/${self:service}-${self:provider.stage}-*
        - !Sub arn:aws:logs:#{AWS::Region}:#{AWS::AccountId}:log-group:/aws/api-gateway/${self:service}-${self:provider.stage}*
        - !Sub arn:aws:logs:#{AWS::Region}:#{AWS::AccountId}:log-group:/aws/apigateway/welcome*
        - !Sub arn:aws:logs:#{AWS::Region}:#{AWS::AccountId}:log-group:API-Gateway-Execution-Logs*
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:Query
      Resource:
        - !GetAtt DynamoTable.Arn

  environment:
    ALGOLIA_APP_ID: ${ssm:/${self:provider.stage}/woahlife/algoliaAppId~true}
    ALGOLIA_APP_KEY: ${ssm:/${self:provider.stage}/woahlife/algoliaAppKey~true}
    ALGOLIA_INDEX_NAME: entries
    DYANMODB_TABLE: !Ref DynamoTable
  logRetentionInDays: 30
  tracing:
    apiGateway: true
    lambda: true
  stackTags:
    app: ${self:service}
  apiKeys:
    - iosApp
  usagePlan:
    quota:
      limit: 250
      offset: 0
      period: DAY
    throttle:
      burstLimit: 20
      rateLimit: 10

functions:
  CreateEntry:
    handler: handler.createEntry
    name: ${self:service}-${self:provider.stage}-create-journal-entry
    description: Create and process an incoming journal entry
    memorySize: 128
    timeout: 30
    alarms:
      - name: 'CreateEntryInvocationAlarm'
        namespace: 'AWS/Lambda'
        metric: Invocations
        threshold: 20
        statistic: Sum
        period: 86400
        evaluationPeriods: 1
        datapointsToAlarm: 1
        comparisonOperator: GreaterThanOrEqualToThreshold
        treatMissingData: notBreaching
    events:
      - http:
          path: create
          method: post
          private: true
  GetEntry:
    handler: handler.getEntry
    name: ${self:service}-${self:provider.stage}-get-journal-entry
    description: Get an existing entry by date
    memorySize: 128
    timeout: 30
    alarms:
      - name: 'GetEntryInvocationAlarm'
        namespace: 'AWS/Lambda'
        metric: Invocations
        threshold: 100
        statistic: Sum
        period: 86400
        evaluationPeriods: 1
        datapointsToAlarm: 1
        comparisonOperator: GreaterThanOrEqualToThreshold
        treatMissingData: notBreaching
    events:
      - http:
          path: entry/{date}
          method: get
          private: true
          request:
            parameters:
              querystrings:
                date: true
  SyncEntriesToSearchIndex:
    handler: handler.syncEntriesToSearchIndex
    name: ${self:service}-${self:provider.stage}-sync-search-index-journal-entry
    description: Sync the dynamodb item update to the search index
    memorySize: 128
    timeout: 60
    alarms:
      - name: 'SyncEntriesInvocationAlarm'
        namespace: 'AWS/Lambda'
        metric: Invocations
        threshold: 100
        statistic: Sum
        period: 86400
        evaluationPeriods: 1
        datapointsToAlarm: 1
        comparisonOperator: GreaterThanOrEqualToThreshold
        treatMissingData: notBreaching
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt DynamoTable.StreamArn
  SearchEntries:
    handler: handler.searchEntries
    name: ${self:service}-${self:provider.stage}-search-journal-entries
    description: Search through journal entries
    memorySize: 128
    timeout: 30
    alarms:
      - name: 'SearchEntriesInvocationAlarm'
        namespace: 'AWS/Lambda'
        metric: Invocations
        threshold: 100
        statistic: Sum
        period: 86400
        evaluationPeriods: 1
        datapointsToAlarm: 1
        comparisonOperator: GreaterThanOrEqualToThreshold
        treatMissingData: notBreaching
    events:
      - http:
          path: search
          method: get
          private: true
          request:
            parameters:
              querystrings:
                query: true

resources:
  Resources:
    DynamoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-entries
        AttributeDefinitions:
          - AttributeName: date
            AttributeType: N
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: date
            KeyType: HASH
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        SSESpecification:
          SSEEnabled: true
          SSEType: KMS
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        Tags:
          - Key: APP
            Value: ${self:provider.stackTags.app}